# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f30179db57846e70a6591be05f71ffd4449914035201cf96c13b7b46d0589d6eb52c08cd55db8f62cd22f4b9f25b3647eb62e3038446067a19ac27db0517374

test:
  secret_key_base: db5a24248315547da66b087595234cdac7f822afcdd4b99ea9e027c06957488435a8b9d062383fc703578a427317d228ed734f292ca38c5888665b4aa8a82dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
